# https://taskfile.dev
version: "3"

# Load environment variables from .env file for configuration context
dotenv:
  - .env

includes:
  lib:
    taskfile: tasks/r_tasks.yml
    flatten: true
    optional: true

tasks:
  build_r_tasks:
    desc: update tasks/r_tasks.yml
    sources:
      - R/utils/Task.R
    generates:
      - tasks/r_tasks.yml
    watch: true
    method: checksum
    cmds:
      - Rscript -e 'box::use(R/utils/Task); Task$write_taskfile()'


